#!/usr/bin/env bash
# Avalhla shared runtime ownership.
# Source this file; do not execute it directly.

AVA_CANONICAL_ROOT="/var/home/VVgbon/Avalhla"
AVA_RUNTIME_LOADED=1

# Canonical path ownership.
# Inherited environment path values are ignored and replaced.
AVA_ROOT="$AVA_CANONICAL_ROOT"
AVA_MEMORY_DIR="$AVA_CANONICAL_ROOT/memory"
AVA_SCRIPTS_DIR="$AVA_CANONICAL_ROOT/scripts"
AVA_CONVERSATIONS_DIR="$AVA_CANONICAL_ROOT/memory/conversations"
AVA_REFLECTIONS_DIR="$AVA_CANONICAL_ROOT/memory/reflections"
AVA_REVIEWED_DIR="$AVA_CANONICAL_ROOT/memory/reviewed"
AVA_KNOWLEDGE_DIR="$AVA_CANONICAL_ROOT/memory/knowledge-base"
AVA_AUTOREAD_DIR="$AVA_CANONICAL_ROOT/memory/auto-read"
AVA_PROFILES_DIR="$AVA_CANONICAL_ROOT/memory/profiles"
AVA_REALITY_DIR="$AVA_CANONICAL_ROOT/memory/reality"

OLLAMA_HOST="http://127.0.0.1:11434"

AVA_MODEL="${AVA_MODEL:-${AVALHLA_MODEL:-avalhla}}"
AVA_CHAT_MODEL="${AVA_CHAT_MODEL:-avalhla-chat}"
AVA_CODE_MODEL="${AVA_CODE_MODEL:-avalhla-code}"
AVA_REVIEW_MODEL="${AVA_REVIEW_MODEL:-avalhla-review}"

AVA_CONVERSATIONS_DIR="${AVA_CONVERSATIONS_DIR:-$AVA_MEMORY_DIR/conversations}"
AVA_REFLECTIONS_DIR="${AVA_REFLECTIONS_DIR:-$AVA_MEMORY_DIR/reflections}"
AVA_REVIEWED_DIR="${AVA_REVIEWED_DIR:-$AVA_MEMORY_DIR/reviewed}"
AVA_KNOWLEDGE_DIR="${AVA_KNOWLEDGE_DIR:-$AVA_MEMORY_DIR/knowledge-base}"
AVA_AUTOREAD_DIR="${AVA_AUTOREAD_DIR:-$AVA_MEMORY_DIR/auto-read}"
AVA_PROFILES_DIR="${AVA_PROFILES_DIR:-$AVA_MEMORY_DIR/profiles}"
AVA_REALITY_DIR="${AVA_REALITY_DIR:-$AVA_MEMORY_DIR/reality}"

export AVA_ROOT AVA_MEMORY_DIR AVA_SCRIPTS_DIR OLLAMA_HOST
export AVA_MODEL AVA_CHAT_MODEL AVA_CODE_MODEL AVA_REVIEW_MODEL
export AVA_CONVERSATIONS_DIR AVA_REFLECTIONS_DIR AVA_REVIEWED_DIR
export AVA_KNOWLEDGE_DIR AVA_AUTOREAD_DIR AVA_PROFILES_DIR AVA_REALITY_DIR
export GIT_PAGER=cat
export PAGER=cat
export SYSTEMD_PAGER=cat
export GH_PAGER=cat
export LESS=
